pdp:
  institutions:
    ids:
      metropolitan_state_university_of_denver: "136000"
      kentucky_state_university: "196800"
      midway_university: "197500"
      rutgers_university_newark: "262902"
      university_of_south_carolina_beaufort: "345000"
      northwest_state_community_college: "867700"
      southeast_kentucky_community_technical_college: "199800"
      university_of_south_carolina_columbia: "344800"
      harrisburg_area_community_college: "327300"
      jefferson_community_and_technical_college: "696100"
      bishop_state_community_college: "103000"
      wallace_state_cc_hanceville: "787100"
      clovis_cc: "474300"
      jf_drake_state_cc: "526000"
      york_county_cc: "3122900"
      dawson_cc: "252900"
      flathead_valley_cc: "677700"
      great_falls_col_montana_state_uni: "931400"
      helena_col_uni_of_montana: "757000"
      miles_cc: "252800"
      montana_state_uni_bozeman: "253200"
      montana_state_uni_northern: "253300"
      montana_state_uni_billings: "253000"
      montana_technological_uni: "253100"
      uni_of_montana_western: "253700"
      uni_of_montana: "253600"
      grand_valley_state_uni: "226800"
      cc_of_allegheny_county: "323100"
      red_rocks_cc: "954300"
      wor_wic_cc: "2073900"
      austin_peay_state_uni: "347800"
      delta_col: "225100"
      san_jose_state_uni: "115500"
      

  secret:
    keys:
      host: "nsc-sftp-host"
      user: "nsc-sftp-user"
      password: "nsc-sftp-password"

institution:
  catalog:
    ids:
      metropolitan_state_university_of_denver: "metropolitan_state_uni_of_denver"
      kentucky_state_university: "kentucky_state_uni"
      midway_university: "midway_uni"
      rutgers_university_newark: "rutgers_uni___newark_campus"
      university_of_south_carolina_beaufort: "uni_of_south_carolina___beaufort"
      northwest_state_community_college: "northwest_state_cc"
      southeast_kentucky_community_technical_college: "southeast_kentucky_community_technical_col"
      university_of_south_carolina_columbia: "None"
      harrisburg_area_community_college: "harrisburg_area_cc"
      jefferson_community_and_technical_college: "jefferson_community_technical_col"
      bishop_state_community_college: "bishop_state_cc"
      nashville_state_community_college: "nashville_state_cc"
      harrisburg_university: "harrisburg_university"
      university_of_central_florida: "uni_of_central_florida"
      south_texas_college: "south_texas_college"
      lee_college: "lee_col"
      central_arizona_col: "central_arizona_col"
      rowan_college_at_burlington_county: "rowan_col_of_burlington_county"
      valencia_college: "valencia_col"
      john_jay_college: "john_jay_col"
      wallace_state_cc_hanceville: "wallace_state_cc_hanceville"
      clovis_cc: "clovis_cc"
      jf_drake_state_cc : "jf_drake_state_cc"
      york_county_cc: "york_county_cc"
      dawson_cc: "dawson_cc"
      flathead_valley_cc: "flathead_valley_cc"
      great_falls_col_montana_state_uni: "great_falls_col_montana_state_uni"
      helena_col_uni_of_montana: "helena_col_uni_of_montana"
      miles_cc: "miles_cc"
      montana_state_uni_bozeman: "montana_state_uni_bozeman"
      montana_state_uni_northern: "montana_state_uni_northern"
      montana_state_uni_billings: "montana_state_uni_billings"
      montana_technological_uni: "montana_technological_uni"
      uni_of_montana_western: "uni_of_montana_western"
      uni_of_montana: "uni_of_montana"
      grand_valley_state_uni: "grand_valley_state_uni"
      uni_of_north_texas: "uni_of_north_texas"
      cc_of_allegheny_county: "cc_of_allegheny_county"
      red_rocks_cc: "red_rocks_cc"
      collin_county_cc_district: "collin_county_cc_district"
      new_york_uni: "new_york_uni"
      city_cols_of_chicago: "city_cols_of_chicago"
      southeast_cc: "southeast_cc"
      wor_wic_cc: "wor_wic_cc"
      suny_oneonta: "suny_oneonta"
      miami_dade_col: "miami_dade_col"
      austin_peay_state_uni: "austin_peay_state_uni"
      indiana_institute_of_technology: "indiana_institute_of_technology"
      motlow_state_cc: "motlow_state_cc"
      suny_brockport: "suny_brockport"
      delta_col: "delta_col"
      san_jose_state_uni: "san_jose_state_uni"

  secure_assets:
      scope: "dataplat-key-vault-sst-secret-scope"
      ids:
        metropolitan_state_university_of_denver: "None"
        kentucky_state_university: "ksu"
        midway_university: "miduni"
        rutgers_university_newark: "rutgers"
        university_of_south_carolina_beaufort: "uscbeau"
        northwest_state_community_college: "nwscc"
        southeast_kentucky_community_technical_college: "skctc"
        university_of_south_carolina_columbia: "None"
        harrisburg_area_community_college: "hacc"
        jefferson_community_and_technical_college: "None"
        bishop_state_community_college: "None"
        nashville_state_community_college: "nscc"
        harrisburg_university: "hu"
        university_of_central_florida: "ucf"
        south_texas_college: "stexcol"
        lee_college: "leecol"
        central_arizona_col: "cac"
        rowan_college_at_burlington_county: "rcbc"
        valencia_college: "valcol"
        john_jay_college: "jjc"
        wallace_state_cc_hanceville: "wscch"
        uni_of_north_texas: "ntx"
        collin_county_cc_district: "ccccd"
        new_york_uni: "nyu"
        city_cols_of_chicago: "ccolc"
        southeast_cc: "secc"
        suny_oneonta: "suny-oneonta"
        miami_dade_col: "miamidade-col"
        indiana_institute_of_technology: "indiana-inst"
        motlow_state_cc: "motlow"
        suny_brockport: "suny-brockport"
